
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  #- "pypy3"  # won't work since it implements Python 3.2.5.

branches:
  only:
    - master
    - next

# command to install dependencies
#install: "pip install -r requirements.txt"

# command to run tests
script:
  - ./imapfw.py -h
  - ./imapfw.py noop
  - python3 -m imapfw.edmp
  - ./imapfw.py unitTests

