
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
  #- "pypy3"  # won't work since it implements Python 3.2.5.

branches:
  only:
    - master
    - next
    - travis # Let testing travis configuration.

before_install:
  - pip install --upgrade pip

# command to install dependencies
install: "pip install -r requirements.txt"

#before_script:
  #- cp -a ./tests "$TRAVIS_BUILD_DIR"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0d4fe7da7dd072da59ea
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never

# command to run tests
script:
  - python3 -m imapfw.edmp
  - python3 -m imapfw.mmp.manager
  - ./imapfw.py -h
  - ./imapfw.py noop
  - ./imapfw.py -c multiprocessing unitTests
  - ./imapfw.py -c threading unitTests
  - ./imapfw.py -r ./tests/syncaccounts.1.rascal -d all noop
  - ./imapfw.py -r ./tests/syncaccounts.1.rascal -d all testRascal
  - ./imapfw.py -r ./tests/syncaccounts.1.rascal -d all examine
  - ./imapfw.py -r ./tests/syncaccounts.1.rascal -d all -c multiprocessing syncAccounts -a AccountA
  - ./imapfw.py -r ./tests/syncaccounts.1.rascal -d all -c threading syncAccounts -a AccountA

# vim: expandtab ts=2 :
